name: 'bds-gametest-run'
description: 'An action to execute and collect results for minecraft gametest framework'
author: 'ScriptAPIOSS'
inputs:
  BDS_PATH:
    required: true
    description: 'The path to BDS on the filesystem'
    default: './bds/'
  TIMEOUT_TICKS:
    required: true
    description: ''
    default: 60000
  AUTOMATION_REPEAT_COUNT:
    required: true
    description: ''
    default: 1
  AUTOMATION_REPEAT_FAILURES_ONLY:
    required: true
    description: ''
    default: true
  MAX_TESTS_PER_BATCH:
    required: true
    description: ''
    default: 20

  PACKS:
    description: ''
  TEST_TAGS:
    description: ''
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'check-square'
  color: 'orange'
